apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-controllers
  namespace: homework
  labels:
    theme: kubernetes-controllers
spec:
  replicas: 3
  selector:
    matchLabels:
      type: nginx-homework
  template:
    metadata:
      labels:
        type: nginx-homework
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - kubernetes-controllers
                      - kubernetes-intro
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8000
        readinessProbe:
          exec:
            command:
              - ls
              - /homework/index.html
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
        volumeMounts:
        - name: shared
          mountPath: /homework
        - name: nginx-conf
          mountPath: /etc/nginx
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", "-c", "rm /homework/index.html" ]
      initContainers:
      - name: prepare-indexhtml
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - https://otus.ru
        volumeMounts:
        - name: shared
          mountPath: "/init"
      volumes:
      - name: shared
        emptyDir: {}
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
