apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-volumes-specific-class
  namespace: homework
  labels:
    theme: kubernetes-volumes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
  storageClassName: otus-homework
