
apiVersion: v1
kind: Pod
metadata:
  name: homework
  namespace: homework
  labels:
    type: homework-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared
      mountPath: /homework
    - name: nginx-conf
      mountPath: /etc/nginx
    lifecycle:
      preStop:
        exec:
          command: [ "/bin/sh", "-c", "rm /homework/index.html" ]
  initContainers:
  - name: prepare-indexhtml
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - https://otus.ru
    volumeMounts:
    - name: shared
      mountPath: "/init"
  volumes:
  - name: shared
    emptyDir: {}
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
        - key: nginx.conf
          path: nginx.conf

